### ISSUE TITLE
CommonJS is not supported

### ISSUE THREAD

**Issue by dy** [sonicdoe/measure-scrollbar#1]
Just tried to `require('measure-scrollbar')()` and failed.

**Comment by sonicdoe** [comment]
measure-scrollbar is currently indeed only available as an ES module. You could use [Babel’s ES2015 modules to CommonJS transform](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/) to transform it to a CommonJS module.

Out of interest, in which environment would you like to use measure-scrollbar? Are you using a bundler?

**Comment by dy** [comment]
I use pure browserify w/o any transforms and heavy dev dependencies. I wonder if that is possible to export a function in ES6 directly.

**Comment by sonicdoe** [comment]
> I use pure browserify w/o any transforms and heavy dev dependencies.

As far as I can tell, there’s no easy way to import ES modules in Browserify (apart from using [babelify](https://github.com/babel/babelify) and [configuring it to transform `node_modules`](https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed) using the [CommonJS transform](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/)).

I’m considering adding a CommonJS version but I’d rather stick with an ES module, to be honest.

> I wonder if that is possible to export a function in ES6 directly.

Sorry, could you explain that in more detail?

**Comment by dy** [comment]
To use es6 modules with browserify, it needs babelify transform, but afaik babel does not allow to export pure function for commonjs to just ‘require(x)()’, it needs ‘require(x).default()’. Which is unfortunate, if I am correct.

**Comment by sonicdoe** [comment]
Ah, yes, that’s mentioned in the info callout at the top in [Babel’s docs](https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/). You can use [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) so you don’t have to do `require('…').default`.

**Comment by dy** [comment]
Ok. Well, bundling packages for ES5 is a nice practice for npm, dev-friendly. There are 4-5 packages for calculating scrollbar, and no one is perfect for the matter. Yours is close, cept for ES6 module.

**Comment by sonicdoe** [comment]
I’ve found [ascjsify](https://github.com/goto-bus-stop/ascjsify) which is a fast Browserify transform for ES modules. This way, `-g ascjsify` is all it takes to use external ES modules with Browserify. [I’ve also documented the usage with other module bundlers in the readme](https://github.com/sonicdoe/measure-scrollbar#module-bundlers).

I understand this is not as nice as just having to do `require('measure-scrollbar')` but I’d rather keep it simple and stick with an ES module. I’m hoping that Browserify will support ES modules in the future.

**Comment by dy** [comment]
Thanks for the really nice transform, did not know about it.

But the point is not the transforming issue, but forcing user to apply global browserify transforms, which is incredibly heavy and slow. Just imagine: I am developing [regl-text](https://github.com/a-vis/text) for [plotly.js](https://github.com/plotly/plotly.js), where I needed this thing - do you know how many dependencies there are in plotly.js? Can you roughly imagine how slow enabling global static transform (parsing/deparsing AST and stuff) will make bundling the dist with 1k+ package deps? So that unfortunately makes your module a blocker for **any** serious package not using ES5 (probably not too many nowadays, who knows).

**Comment by sonicdoe** [comment]
Given the popularity of Browserify (and the pain of using ES modules with it), I’ve decided to add a CommonJS version (see https://github.com/sonicdoe/measure-scrollbar/commit/feee72e0483c564b7145e1d980e020fde3b4f627). In v1.1.0, you can now use `require('measure-scrollbar/commonjs')`.

**Comment by dy** [comment]
https://twitter.com/dan_abramov/status/1009179550134296577?s=21

**Comment by sonicdoe** [comment]
Thanks for following up and linking to this tweet. I understand the recommendation regarding experimental syntax but I’m not so sure about ES modules. Since this particular package only targets browsers, I don’t need to worry about Node.js’s experimental support.

[`pkg.module`](https://github.com/rollup/rollup/wiki/pkg.module) might the best solution to distribute both CommonJS and ES module versions.
