### ISSUE TITLE
On OSX zero is always returned

### ISSUE THREAD

**Issue by lqc** [sonicdoe/measure-scrollbar#3]
This is because scrollbars are hidden by default and show only after user is actually scrolling.

**Comment by sonicdoe** [comment]
This is intentional because the scrollbar does not affect the layout during the time it is visible. What’s the use case for getting the width of this hidden-by-default scrollbar?

**Comment by lqc** [comment]
It might not affect layout, but it does cover page content. For example, if you have a list of items and you begin scrolling horizontally, the last item on the list will get covered.

**Comment by sonicdoe** [comment]
Do you perhaps know of a way to get the scrollbar’s width in that case? Since it doesn’t affect the layout, I’m guessing this is quite hard and I’d rather refrain from hard-coding any values.
